apiVersion: apps/v1
kind: Deployment
metadata:
  name: convercao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: convercao-temperatura
  template:
    metadata:
      labels:
        app: convercao-temperatura
    spec:
      containers:
      - name: convercao-temperatura
        image: dleal/conversao-temperatura:v1
---
apiVersion: v1
kind: Service
metadata:
  name: convercao-temperatura
spec:
  selector:
    app: convercao-temperatura
  ports:
  - port: 8085
    targetPort: 8080
    nodePort: 30001 
  type: NodePort 


